# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
- name: environment
  type: string


stages:
- stage: Build
  jobs:
    - job: Build
      pool:
        vmImage: ubuntu-latest
      steps:
      - script: echo "deu"
        displayName: 'Install dependencies'

# steps:
# - script: echo "Estou no android (${{ parameters.environment }})"
#   displayName: Android
# - task: CmdLine@2
#   displayName: Build Android
#   condition: succeeded()
#   inputs:
#     script: |
#       bundle exec fastlane android build version_code:$(Build.BuildId)

# - task: CopyFiles@2
#   displayName: Save compiled binary
#   inputs:
#     contents: android/**/*.apk
#     TargetFolder: '$(Build.ArtifactStagingDirectory)'
#     CleanTargetFolder: true
#     OverWrite: true
