# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main
  - dev

# strategy:
#   matrix:
#     Android:
#       imageName: 'ubuntu-latest'
#       platformName: android
#     iOS:
#       imageName: 'macOS-latest'
#       platformName: ios

# se vamos ter um azure-pipelines-sandbox e um production
# então podemos deixar fixo o valor dessa env
variables:
- name: environment
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    value: production
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
    value: sandbox

jobs:
- job: Build
  pool:
    vmImage: macOS-latest
  strategy:
    matrix:
      Android:
        imageName: 'ubuntu-latest'
        platformName: android
      iOS:
        imageName: 'macOS-latest'
        platformName: ios
  steps:
  # - template: .azure/build.yml
  #   parameters:
  #     name: $(platformName)
  #     environment: ${{ variables.environment }}
  #     pool:
  #       vmImage: $(imageName)

  - template: .azure/build.yml