# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

strategy:
  matrix:
    Android:
      imageName: 'macOS-latest'
      platformName: android
    # iOS:
    #   imageName: 'macOS-latest'
    #   platformName: ios

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSource: 'fromFile'
    versionFilePath: .nvmrc
  displayName: 'Install Node.js'

- script: |
    gem install bundler   
  displayName: 'Ruby bundle setup'

# Android tasks
# =======================
- task: CmdLine@2
  displayName: Build Android
  condition: and(succeeded(), eq(variables['platformName'], 'android'))
  inputs:
    script: |
      bundle exec fastlane android build --env sandbox version_code:$(Build.BuildId)

# Android tasks
# =======================
- task: CmdLine@2
  displayName: Build iOS
  condition: and(succeeded(), eq(variables['platformName'], 'ios'))
  inputs:
    script: |
      bundle exec fastlane ios build
