# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main
  - dev

# strategy:
#   matrix:
#     Android:
#       imageName: 'ubuntu-latest'
#       platformName: android
#     iOS:
#       imageName: 'macOS-latest'
#       platformName: ios

# se vamos ter um azure-pipelines-sandbox e um production
# então podemos deixar fixo o valor dessa env
variables:
- name: environment
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    value: production
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/dev') }}:
    value: sandbox

# pool:
#   vmImage: $(imageName)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    strategy:
      matrix:
        Python35:
          PYTHON_VERSION: '3.5'
        Python36:
          PYTHON_VERSION: '3.6'
        Python37:
          PYTHON_VERSION: '3.7'
      maxParallel: 2
    steps:
      - template: .azure/android.yml # TODO: carregar um arquivo com nome dinâmico
        parameters:
          environment: ${{ variables.environment }}
          platformName: $(platformName)
