# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: Environment
    type: string
  - name: Platform
    type: string
  - name: Contents
    type: string

jobs:
  - job: Build
    steps:
      - script: |
          man ls > android/app/src/release.${{ parameters.Environment }}.apk
        displayName: Android apk

      - script: |
          man ls > android/app/src/main/release.${{ parameters.Environment }}.aab
        displayName: Android aab

      - script: |
          man rm > ios/ipa/release.${{ parameters.Environment }}.ipa
        displayName: iOS

      - task: CopyFiles@2
        displayName: Copy compiled binary
        inputs:
          contents: ${{ parameters.Contents }}
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          CleanTargetFolder: true
          OverWrite: true

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: ${{parameters.Platform}}.${{ parameters.Environment }}.$(Build.BuildId)
        displayName: Publish artifact
