# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

jobs:
  - job: Build
    strategy:
      matrix:
        Android:
          imageName: 'ubuntu-latest'
          platform: android
        iOS:
          imageName: 'macOS-latest'
          platform: ios
    pool:
      vmImage: $(imageName)
    steps:
      - task: CmdLine@2
        displayName: yarn/npm install
        inputs:
          script: echo "olá"

      - task: CmdLine@2
        displayName: Test
        inputs:
          script: |
            echo ${{ variables.environment }} - $(platform) - $(Build.BuildId)