# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: environment
    type: string

jobs:
- job: Build
  strategy:
    matrix:
      Android:
        imageName: 'ubuntu-latest'
        platform: android
      iOS:
        imageName: 'macOS-latest'
        platform: ios

  pool:
    vmImage: $(imageName)

  steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'fromFile'
        versionFilePath: .nvmrc
      displayName: 'Install Node.js'

    - task: CmdLine@2
      displayName: yarn/npm install
      inputs:
        script: yarn

    - task: CmdLine@2
      displayName: Install fastlane using Gemfile
      inputs:
        script: |
          sudo gem install bundler
          sudo bundle install

    - task: CmdLine@2
      displayName: Build for $(platform)
      condition: succeeded()
      inputs:
        script: |
          bundle exec fastlane $(platform) build \
            env:${{ parameters.environment }} version_code:$(Build.BuildId)

    - task: CopyFiles@2
      displayName: Save compiled binary
      condition: succeeded()
      inputs:
        contents: android/**/*.apk
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        CleanTargetFolder: true
        OverWrite: true
