# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - dev

variables:
- name: environment
  value: sandbox

strategy:
  matrix:
    Android:
      imageName: 'ubuntu-latest'
      platform: android
    iOS:
      imageName: 'macOS-latest'
      platform: ios

pool:
  vmImage: $(imageName)

extends:
  template: azure-pipelines.yml
