# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript


parameters:
  - name: Environment
    type: string
    - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/disposable/production') }}:
        default: production
    - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/disposable/sandbox') }}:
        default: sandbox
  - name: Platform
    type: string
  - name: Contents
    type: string

jobs:
  - job: Build
    steps:
      - task: CmdLine@2
        displayName: ${{ variables['Environment'] }}
        inputs:
          script: echo ${{variables['Environment']}} - ${{variables.Environment}}

      - task: NodeTool@0
        inputs:
          versionSource: 'fromFile'
          versionFilePath: .nvmrc
        displayName: 'Install Node.js'

      - task: CmdLine@2
        displayName: yarn/npm install
        inputs:
          script: yarn

      - task: CmdLine@2
        displayName: Install fastlane using Gemfile
        inputs:
          script: |
            sudo gem install bundler
            sudo bundle install

      - task: CmdLine@2
        displayName: Run fastlane
        condition: succeeded()
        inputs:
          script: |
            bundle exec fastlane ${{ parameters.Platform }} build \
              env:${{ variables.Environment }} version_code:$(Build.BuildId)

      - task: CopyFiles@2
        displayName: Copy compiled binary
        inputs:
          contents: ${{ parameters.Contents }}
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
          CleanTargetFolder: true
          OverWrite: true

      - publish: $(Build.ArtifactStagingDirectory)
        artifact: ${{ parameters.Platform }}.${{ variables.Environment }}.$(Build.BuildId)
        displayName: Publish artifact
