# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: environment
    type: string
  - name: name
    type: string
  - name: pool
    type: string

jobs:
  - job: ${{ parameters.name }}
    pool: ${{ parameters.pool }}
    steps:
      - script: echo "npm install"
      - script: echo "npm test"
      - ${{ if eq(parameters.name, 'android') }}:
        - script: echo "Android"
          displayName: Android
      - ${{ if eq(parameters.name, 'ios') }}:
        - script: echo "ios"
          displayName: iOS