# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: environment
    type: string
  - name: platform
    type: string

steps:
  - task: CmdLine@2
    displayName: Build parameters.platform
    condition: succeeded()
    inputs:
      script: |
        PLATFORM_NAME=${{lower(parameters.platform)}}
        echo $PLATFORM_NAME - ${{parameters.environment}} - $(Build.BuildId)
        # bundle exec fastlane ${{ lower(parameters.platform) }} build env:${{ parameters.environment }} version_code:$(Build.BuildId)