# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

parameters:
  - name: environment
    type: string
  - name: platform
    type: string
  - name: job
    type: string
    default: $(Agent.JobName)

steps:
  - task: CmdLine@2
    displayName: Build ${{split(parameters.job, 'Job ')[1]}}
    condition: succeeded()
    inputs:
      script: |
        bundle exec fastlane ${{parameters.platform}} build \
          env:${{parameters.environment}} version_code:$(Build.BuildId)