# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - disposable/sandbox
  - disposable/production

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: ../azure-pipelines.yml
  parameters:
    Platform: android
    Contents: |
      android/**/*.apk
      android/**/*.aab
